<?xml version="1.0" encoding="UTF-8"?>
<!--Created with WSDLGenerator 2.0.0 by Amadeus SAS-->
<!--  Amadeus Proprietary and Confidential Information: unauthorized use and disclosure strictly forbidden. 2015 - Amadeus s.a.s - All Rights Reserved.  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:amasec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:awsl="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3" xmlns:int="http://wsdl.amadeus.com/Ticket_RebookAndRepricePNR_v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://wsdl.amadeus.com/Ticket_RebookAndRepricePNR_v1_v4" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.amadeus.com/Ticket_RebookAndRepricePNR_v1_v4" name="BT6SKR_Ticket_RebookAndRepricePNR_1.0_4.0">
  <wsdl:documentation>Versions: [interface: 1.0 ; technical: 4.0]</wsdl:documentation>
  <wsp:Policy wsu:Id="MessagingPolicy">
    <wsam:Addressing wsp:Optional="true">
      <wsp:Policy>
        <wsam:AnonymousResponses />
      </wsp:Policy>
    </wsam:Addressing>
  </wsp:Policy>
  <wsp:Policy wsu:Id="AmadeusPolicy">
    <wsp:PolicyReference URI="#MessagingPolicy" />
  </wsp:Policy>
  <wsdl:import namespace="http://wsdl.amadeus.com/Ticket_RebookAndRepricePNR_v1" location="Ticket_RebookAndRepricePNR_1.0.wsdl" />
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="AMA/2012B/AMA_WS_Session.xsd" namespace="http://xml.amadeus.com/2010/06/Session_v3" />
      <xs:import schemaLocation="AMA_WSLink.xsd" namespace="http://wsdl.amadeus.com/2010/06/ws/Link_v1" />
      <xs:import schemaLocation="AMA/2012B/AMA_SecurityHostedUser.xsd" namespace="http://xml.amadeus.com/2010/06/Security_v1" />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="Session_3.000">
    <wsdl:part name="session" element="awsse:Session" />
  </wsdl:message>
  <wsdl:message name="TransactionFlowLink_1.0">
    <wsdl:part name="link" element="awsl:TransactionFlowLink" />
  </wsdl:message>
  <wsdl:message name="AMA_SecurityHostedUser_1.000">
    <wsdl:part name="security" element="amasec:AMA_SecurityHostedUser" />
  </wsdl:message>
  <wsdl:binding name="Ticket_RebookAndRepricePNR_Binding" type="int:Ticket_RebookAndRepricePNR_PT">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Ticket_RebookAndRepricePNR">
      <soap:operation soapAction="http://webservices.amadeus.com/Ticket_RebookAndRepricePNR_1.0" />
      <wsdl:input>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
        <soap:header message="tns:AMA_SecurityHostedUser_1.000" part="security" use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
        <soap:header message="tns:Session_3.000" part="session" use="literal" />
        <soap:header message="tns:TransactionFlowLink_1.0" part="link" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Ticket_RebookAndRepricePNR_Service">
    <wsdl:port binding="tns:Ticket_RebookAndRepricePNR_Binding" name="Ticket_RebookAndRepricePNR_Port">
      <wsp:PolicyReference URI="#AmadeusPolicy" />
      <soap:address location="https://nodeD3.test.webservices.amadeus.com/1ASIWSKRBT6" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
<!--1F8B08000000000000007D8D4D0BC2301044EFFD157B54C4B2AD20925BA950C40F4A5AF028315D31B4DD843415FCF706BD0B731AE6BDA988C9AB602C4330234D418D4E408EF9668D790CB4CFD94F9D7A036E45B613B1A9CEED0A512026D7667F82EA67B01E5EE4A7288A788A2926E560880328E706A3BF17029ADE1377733A04583447B98C8AA206562309688DEE29DC24DDADED0BEE24396F34D517991C38907F28FD7705197E004EF52D06CE000000-->
